-- ==============================================================
-- FILE : V2ES_RWC.VHD  -  DO NOT EDIT THIS FILE
-- ==============================================================
--
-- This file is part of the Hardware Interface Layer (H.I.L) of
-- your project when using your HERON-FPGA3 module.
--
-- This file must NOT be modified by users of the Module.
--
-- ==============================================================
--
-- CAUTION : ONLY USED FOR VIRTEX2 ENGINEERING SAMPLES !!!
--
-- ==============================================================
--
--  Date        : 28/02/2002
--  Author      : R. Williams - HUNT ENGINEERING
--
-- ==============================================================
--
--  Ver     Modified By      Date      Changes
--  ---     -----------      ----      -------
--  1.0     R. Williams    28-02-02    First Written
--  1.1     R. Williams    08-05-02    Syntax change made to all
--                                     instanciated components,
--                                     (changed '0' to GND)
--                                     for compatibility with
--                                     ModelSim5.5b.
--  1.2     R. Williams    11-06-02    Added 1ns delay on paths
--                                     from inferred flip-flops
--                                     to instantiated flip-flops
--                                     to prevent setup violations
--                                     in functional simulation.
--  2.0     R. Williams    10-10-02    New components added for
--                                     interfacing to all six HERON
--                                     input FIFOs and all six HERON
--                                     output FIFOs at the same time.
--                                     Added component HE_RD_6F in
--                                     place of component HE_RD_1F.
--                                     Added component HE_WR_6F in
--                                     place of component HE_WR_1F.
--  2.1     R. Williams    20-01-03    Changes made to the HSB
--                                     mastering functions, and 
--                                     additional registering added
--                                     to the AE flag to ensure
--                                     correct reading from HEPC8s.
--
-- ==============================================================


-- ==============================================================

--  Module      : ES_RD_LF
--  Description : IN FIFO Clock - low frequency (less than 60 MHz)

library IEEE;
  use IEEE.std_logic_1164.all;

-- synopsys translate_off
library UNISIM;
  use UNISIM.vcomponents.all;
-- synopsys translate_on

entity ES_RD_LF is
  port (
    -- External PADS
    DCLK : in  std_logic;
    FCLK : out std_logic;
    -- Module I/Os
    RST  : in  std_logic;
    CLK  : in  std_logic;
    GCLK : out std_logic
  );
end ES_RD_LF;

architecture RTL of ES_RD_LF is

  component CLKDLL
    port (CLKIN   : in  std_logic;
          CLKFB   : in  std_logic;
          RST     : in  std_logic;
          CLK0    : out std_logic;
          CLK90   : out std_logic;
          CLK180  : out std_logic;
          CLK270  : out std_logic;
          CLK2X   : out std_logic;
          CLKDV   : out std_logic;
          LOCKED  : out std_logic);
  end component;

  component BUFG
    port(I : in  std_logic;
         O : out std_logic);
  end component;

  signal GND   : std_logic;
  signal CLKIN : std_logic;
  signal CLK0  : std_logic;
  signal GCLK0 : std_logic;

  attribute LOC : string;
  attribute LOC of iDLL : label is "DCM_X1Y0";

begin

  GND <= '0';

  FCLK <= CLK;    -- OBUF_F_24 (instanciation in the top level)

  CLKIN <= DCLK;  -- IBUFG (instanciation in the top level)

  iDLL : CLKDLL
    port map ( CLKIN => CLKIN,
               CLKFB => GCLK0,
               RST   => GND,
               CLK0  => CLK0 );

  bGCK : BUFG port map (I=>CLK0, O=>GCLK0);
  GCLK <= GCLK0;

end RTL;

-- ==============================================================

--  Module      : ES_RD_HF
--  Description : IN FIFO Clock - high frequency (greater than 60 MHz)

library IEEE;
  use IEEE.std_logic_1164.all;

-- synopsys translate_off
library UNISIM;
  use UNISIM.vcomponents.all;
-- synopsys translate_on

entity ES_RD_HF is
  port (
    -- External PADS
    DCLK : in  std_logic;
    FCLK : out std_logic;
    -- Module I/Os
    RST  : in  std_logic;
    CLK  : in  std_logic;
    GCLK : out std_logic
  );
end ES_RD_HF;

architecture RTL of ES_RD_HF is

  component CLKDLLHF
    port (CLKIN  : in  std_logic;
          CLKFB  : in  std_logic;
          RST    : in  std_logic;
          CLK0   : out std_logic;
          CLK180 : out std_logic;
          CLKDV  : out std_logic;
          LOCKED : out std_logic);
  end component;

  component BUFG
    port(I : in  std_logic;
         O : out std_logic);
  end component;

  signal R1      : std_logic;
  signal R2      : std_logic;
  signal RST_DLL : std_logic;
  signal CLKIN   : std_logic;
  signal CLK0    : std_logic;
  signal GCLK0   : std_logic;

  attribute LOC : string;
  attribute LOC of iDLL : label is "DCM_X1Y0";

begin

  FCLK <= CLK;    -- OBUF_F_24 (instanciation in the top level)

  CLKIN <= DCLK;  -- IBUFG (instanciation in the top level)

  process(CLK)
  begin
    if rising_edge(CLK) then
      R1 <= RST;
      R2 <= R1;
      RST_DLL <= R2 AND (NOT R1);
    end if;
  end process;

  iDLL : CLKDLLHF
    port map ( CLKIN => CLKIN,
               CLKFB => GCLK0,
               RST   => RST_DLL,
               CLK0  => CLK0 );

  bGCK : BUFG port map (I=>CLK0, O=>GCLK0);
  GCLK <= GCLK0;

end RTL;

-- ==============================================================

--  Module      : ES_WR_LF
--  Description : OUT FIFO Clock - low frequency (less than 60 MHz)

library IEEE;
  use IEEE.std_logic_1164.all;

-- synopsys translate_off
library UNISIM;
  use UNISIM.vcomponents.all;
-- synopsys translate_on

entity ES_WR_LF is
  port (
    -- External PADS
    DCLK : in  std_logic;
    FCLK : out std_logic;
    -- Module I/Os
    RST  : in  std_logic;
    CLK  : in  std_logic;
    GCLK : out std_logic
  );
end ES_WR_LF;

architecture RTL of ES_WR_LF is

  component CLKDLL
    port (CLKIN   : in  std_logic;
          CLKFB   : in  std_logic;
          RST     : in  std_logic;
          CLK0    : out std_logic;
          CLK90   : out std_logic;
          CLK180  : out std_logic;
          CLK270  : out std_logic;
          CLK2X   : out std_logic;
          CLKDV   : out std_logic;
          LOCKED  : out std_logic);
  end component;

  component BUFG
    port(I : in  std_logic;
         O : out std_logic);
  end component;

  signal GND   : std_logic;
  signal CLKIN : std_logic;
  signal CLK0  : std_logic;
  signal GCLK0 : std_logic;

  attribute LOC : string;
  attribute LOC of iDLL : label is "DCM_X2Y0";

begin

  GND <= '0';

  FCLK <= CLK;    -- OBUF_F_24 (instanciation in the top level)

  CLKIN <= DCLK;  -- IBUFG (instanciation in the top level)

  iDLL : CLKDLL
    port map ( CLKIN => CLKIN,
               CLKFB => GCLK0,
               RST   => GND,
               CLK0  => CLK0 );

  bGCK : BUFG port map (I=>CLK0, O=>GCLK0);
  GCLK <= GCLK0;

end RTL;

-- ==============================================================

--  Module      : ES_WR_HF
--  Description : OUT FIFO Clock - high frequency (greater than 60 MHz)

library IEEE;
  use IEEE.std_logic_1164.all;

-- synopsys translate_off
library UNISIM;
  use UNISIM.vcomponents.all;
-- synopsys translate_on

entity ES_WR_HF is
  port (
    -- External PADS
    DCLK : in  std_logic;
    FCLK : out std_logic;
    -- Module I/Os
    RST  : in  std_logic;
    CLK  : in  std_logic;
    GCLK : out std_logic
  );
end ES_WR_HF;

architecture RTL of ES_WR_HF is

  component CLKDLLHF
    port (CLKIN  : in  std_logic;
          CLKFB  : in  std_logic;
          RST    : in  std_logic;
          CLK0   : out std_logic;
          CLK180 : out std_logic;
          CLKDV  : out std_logic;
          LOCKED : out std_logic);
  end component;

  component BUFG
    port(I : in  std_logic;
         O : out std_logic);
  end component;

  signal R1      : std_logic;
  signal R2      : std_logic;
  signal RST_DLL : std_logic;
  signal CLKIN   : std_logic;
  signal CLK0    : std_logic;
  signal GCLK0   : std_logic;

  attribute LOC : string;
  attribute LOC of iDLL : label is "DCM_X2Y0";

begin

  FCLK <= CLK;    -- OBUF_F_24 (instanciation in the top level)

  CLKIN <= DCLK;  -- IBUFG (instanciation in the top level)

  process(CLK)
  begin
    if rising_edge(CLK) then
      R1 <= RST;
      R2 <= R1;
      RST_DLL <= R2 AND (NOT R1);
    end if;
  end process;

  iDLL : CLKDLLHF
    port map ( CLKIN => CLKIN,
               CLKFB => GCLK0,
               RST   => RST_DLL,
               CLK0  => CLK0 );

  bGCK : BUFG port map (I=>CLK0, O=>GCLK0);
  GCLK <= GCLK0;

end RTL;

