//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Files.rc
//
#define BlankPage                       1
#define Product                         114
#define TimeSpan                        188
#define Observation                     562
#define PageTimeSpan                    563
#define PageObservation                 564
#define PageProduct                     565

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
