[COREGEN.VERILOG Component Instantiation.iq_out_fifo]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="iq_out_fifo YourInstanceName ("
text007="    .din(din),"
text008="    .wr_en(wr_en),"
text009="    .wr_clk(wr_clk),"
text010="    .rd_en(rd_en),"
text011="    .rd_clk(rd_clk),"
text012="    .ainit(ainit),"
text013="    .dout(dout),"
text014="    .full(full),"
text015="    .empty(empty));"
text016=""
text017=" "
type=template
[COREGEN.VERILOG Component Instantiation.i_out_fifo]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="i_out_fifo YourInstanceName ("
text007="    .din(din),"
text008="    .wr_en(wr_en),"
text009="    .wr_clk(wr_clk),"
text010="    .rd_en(rd_en),"
text011="    .rd_clk(rd_clk),"
text012="    .ainit(ainit),"
text013="    .dout(dout),"
text014="    .full(full),"
text015="    .empty(empty));"
text016=""
text017=" "
type=template
[COREGEN.VERILOG Component Instantiation.mydcc]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="mydcc YourInstanceName ("
text007="    .DIN(DIN),"
text008="    .ND(ND),"
text009="    .RDY(RDY),"
text010="    .RFD(RFD),"
text011="    .CLK(CLK),"
text012="    .DOUT_I(DOUT_I),"
text013="    .DOUT_Q(DOUT_Q));"
text014=""
text015=" "
type=template
[COREGEN.VERILOG Component Instantiation.myddc]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="myddc YourInstanceName ("
text007="    .DIN(DIN),"
text008="    .ND(ND),"
text009="    .RDY(RDY),"
text010="    .RFD(RFD),"
text011="    .CLK(CLK),"
text012="    .ADDR(ADDR),"
text013="    .LD_DIN(LD_DIN),"
text014="    .WE(WE),"
text015="    .SEL(SEL),"
text016="    .DOUT_I(DOUT_I),"
text017="    .DOUT_Q(DOUT_Q));"
text018=""
text019=" "
type=template
[COREGEN.VERILOG Component Instantiation.noisedatafifo]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="noisedatafifo YourInstanceName ("
text007="    .din(din),"
text008="    .wr_en(wr_en),"
text009="    .wr_clk(wr_clk),"
text010="    .rd_en(rd_en),"
text011="    .rd_clk(rd_clk),"
text012="    .ainit(ainit),"
text013="    .dout(dout),"
text014="    .full(full),"
text015="    .empty(empty));"
text016=""
text017=" "
type=template
[COREGEN.VERILOG Component Instantiation.q_out_fifo]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="q_out_fifo YourInstanceName ("
text007="    .din(din),"
text008="    .wr_en(wr_en),"
text009="    .wr_clk(wr_clk),"
text010="    .rd_en(rd_en),"
text011="    .rd_clk(rd_clk),"
text012="    .ainit(ainit),"
text013="    .dout(dout),"
text014="    .full(full),"
text015="    .empty(empty));"
text016=""
text017=" "
type=template
[COREGEN.VERILOG Component Instantiation.rawfifo255x14]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="rawfifo255x14 YourInstanceName ("
text007="    .din(din),"
text008="    .wr_en(wr_en),"
text009="    .wr_clk(wr_clk),"
text010="    .rd_en(rd_en),"
text011="    .rd_clk(rd_clk),"
text012="    .ainit(ainit),"
text013="    .dout(dout),"
text014="    .full(full),"
text015="    .empty(empty));"
text016=""
text017=" "
type=template
[COREGEN.VERILOG Component Instantiation.spfilter]
text000=" "
text001=" "
text002="// The following must be inserted into your Verilog file for this"
text003="// core to be instantiated. Change the instance name and port connections"
text004="// (in parentheses) to your own signal names."
text005=" "
text006="spfilter YourInstanceName ("
text007="    .CLK(CLK),"
text008="    .RESET(RESET),"
text009="    .ND(ND),"
text010="    .RDY(RDY),"
text011="    .RFD(RFD),"
text012="    .DIN(DIN),"
text013="    .DOUT(DOUT));"
text014=""
text015=" "
type=template
[COREGEN.VHDL Component Instantiation.iq_out_fifo]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component iq_out_fifo"
text005="    port ("
text006="    din: IN std_logic_VECTOR(31 downto 0);"
text007="    wr_en: IN std_logic;"
text008="    wr_clk: IN std_logic;"
text009="    rd_en: IN std_logic;"
text010="    rd_clk: IN std_logic;"
text011="    ainit: IN std_logic;"
text012="    dout: OUT std_logic_VECTOR(31 downto 0);"
text013="    full: OUT std_logic;"
text014="    empty: OUT std_logic);"
text015="end component;"
text016=""
text017=""
text018=""
text019=" "
text020="-------------------------------------------------------------"
text021=" "
text022="-- The following code must appear in the VHDL architecture body."
text023="-- Substitute your own instance name and net names."
text024=" "
text025="your_instance_name : iq_out_fifo"
text026="        port map ("
text027="            din => din,"
text028="            wr_en => wr_en,"
text029="            wr_clk => wr_clk,"
text030="            rd_en => rd_en,"
text031="            rd_clk => rd_clk,"
text032="            ainit => ainit,"
text033="            dout => dout,"
text034="            full => full,"
text035="            empty => empty);"
text036=" "
type=template
[COREGEN.VHDL Component Instantiation.i_out_fifo]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component i_out_fifo"
text005="    port ("
text006="    din: IN std_logic_VECTOR(31 downto 0);"
text007="    wr_en: IN std_logic;"
text008="    wr_clk: IN std_logic;"
text009="    rd_en: IN std_logic;"
text010="    rd_clk: IN std_logic;"
text011="    ainit: IN std_logic;"
text012="    dout: OUT std_logic_VECTOR(31 downto 0);"
text013="    full: OUT std_logic;"
text014="    empty: OUT std_logic);"
text015="end component;"
text016=""
text017=""
text018=""
text019=" "
text020="-------------------------------------------------------------"
text021=" "
text022="-- The following code must appear in the VHDL architecture body."
text023="-- Substitute your own instance name and net names."
text024=" "
text025="your_instance_name : i_out_fifo"
text026="        port map ("
text027="            din => din,"
text028="            wr_en => wr_en,"
text029="            wr_clk => wr_clk,"
text030="            rd_en => rd_en,"
text031="            rd_clk => rd_clk,"
text032="            ainit => ainit,"
text033="            dout => dout,"
text034="            full => full,"
text035="            empty => empty);"
text036=" "
type=template
[COREGEN.VHDL Component Instantiation.mydcc]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component mydcc"
text005="    port ("
text006="    DIN: IN std_logic_VECTOR(13 downto 0);"
text007="    ND: IN std_logic;"
text008="    RDY: OUT std_logic;"
text009="    RFD: OUT std_logic;"
text010="    CLK: IN std_logic;"
text011="    DOUT_I: OUT std_logic_VECTOR(29 downto 0);"
text012="    DOUT_Q: OUT std_logic_VECTOR(29 downto 0));"
text013="end component;"
text014=""
text015=""
text016=""
text017=" "
text018="-------------------------------------------------------------"
text019=" "
text020="-- The following code must appear in the VHDL architecture body."
text021="-- Substitute your own instance name and net names."
text022=" "
text023="your_instance_name : mydcc"
text024="        port map ("
text025="            DIN => DIN,"
text026="            ND => ND,"
text027="            RDY => RDY,"
text028="            RFD => RFD,"
text029="            CLK => CLK,"
text030="            DOUT_I => DOUT_I,"
text031="            DOUT_Q => DOUT_Q);"
text032=" "
type=template
[COREGEN.VHDL Component Instantiation.myddc]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component myddc"
text005="    port ("
text006="    DIN: IN std_logic_VECTOR(13 downto 0);"
text007="    ND: IN std_logic;"
text008="    RDY: OUT std_logic;"
text009="    RFD: OUT std_logic;"
text010="    CLK: IN std_logic;"
text011="    ADDR: IN std_logic_VECTOR(4 downto 0);"
text012="    LD_DIN: IN std_logic_VECTOR(31 downto 0);"
text013="    WE: IN std_logic;"
text014="    SEL: IN std_logic;"
text015="    DOUT_I: OUT std_logic_VECTOR(29 downto 0);"
text016="    DOUT_Q: OUT std_logic_VECTOR(29 downto 0));"
text017="end component;"
text018=""
text019=""
text020=""
text021=" "
text022="-------------------------------------------------------------"
text023=" "
text024="-- The following code must appear in the VHDL architecture body."
text025="-- Substitute your own instance name and net names."
text026=" "
text027="your_instance_name : myddc"
text028="        port map ("
text029="            DIN => DIN,"
text030="            ND => ND,"
text031="            RDY => RDY,"
text032="            RFD => RFD,"
text033="            CLK => CLK,"
text034="            ADDR => ADDR,"
text035="            LD_DIN => LD_DIN,"
text036="            WE => WE,"
text037="            SEL => SEL,"
text038="            DOUT_I => DOUT_I,"
text039="            DOUT_Q => DOUT_Q);"
text040=" "
type=template
[COREGEN.VHDL Component Instantiation.noisedatafifo]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component noisedatafifo"
text005="    port ("
text006="    din: IN std_logic_VECTOR(13 downto 0);"
text007="    wr_en: IN std_logic;"
text008="    wr_clk: IN std_logic;"
text009="    rd_en: IN std_logic;"
text010="    rd_clk: IN std_logic;"
text011="    ainit: IN std_logic;"
text012="    dout: OUT std_logic_VECTOR(13 downto 0);"
text013="    full: OUT std_logic;"
text014="    empty: OUT std_logic);"
text015="end component;"
text016=""
text017=""
text018=""
text019=" "
text020="-------------------------------------------------------------"
text021=" "
text022="-- The following code must appear in the VHDL architecture body."
text023="-- Substitute your own instance name and net names."
text024=" "
text025="your_instance_name : noisedatafifo"
text026="        port map ("
text027="            din => din,"
text028="            wr_en => wr_en,"
text029="            wr_clk => wr_clk,"
text030="            rd_en => rd_en,"
text031="            rd_clk => rd_clk,"
text032="            ainit => ainit,"
text033="            dout => dout,"
text034="            full => full,"
text035="            empty => empty);"
text036=" "
type=template
[COREGEN.VHDL Component Instantiation.q_out_fifo]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component q_out_fifo"
text005="    port ("
text006="    din: IN std_logic_VECTOR(31 downto 0);"
text007="    wr_en: IN std_logic;"
text008="    wr_clk: IN std_logic;"
text009="    rd_en: IN std_logic;"
text010="    rd_clk: IN std_logic;"
text011="    ainit: IN std_logic;"
text012="    dout: OUT std_logic_VECTOR(31 downto 0);"
text013="    full: OUT std_logic;"
text014="    empty: OUT std_logic);"
text015="end component;"
text016=""
text017=""
text018=""
text019=" "
text020="-------------------------------------------------------------"
text021=" "
text022="-- The following code must appear in the VHDL architecture body."
text023="-- Substitute your own instance name and net names."
text024=" "
text025="your_instance_name : q_out_fifo"
text026="        port map ("
text027="            din => din,"
text028="            wr_en => wr_en,"
text029="            wr_clk => wr_clk,"
text030="            rd_en => rd_en,"
text031="            rd_clk => rd_clk,"
text032="            ainit => ainit,"
text033="            dout => dout,"
text034="            full => full,"
text035="            empty => empty);"
text036=" "
type=template
[COREGEN.VHDL Component Instantiation.rawfifo255x14]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component rawfifo255x14"
text005="    port ("
text006="    din: IN std_logic_VECTOR(13 downto 0);"
text007="    wr_en: IN std_logic;"
text008="    wr_clk: IN std_logic;"
text009="    rd_en: IN std_logic;"
text010="    rd_clk: IN std_logic;"
text011="    ainit: IN std_logic;"
text012="    dout: OUT std_logic_VECTOR(13 downto 0);"
text013="    full: OUT std_logic;"
text014="    empty: OUT std_logic);"
text015="end component;"
text016=""
text017=""
text018=""
text019=" "
text020="-------------------------------------------------------------"
text021=" "
text022="-- The following code must appear in the VHDL architecture body."
text023="-- Substitute your own instance name and net names."
text024=" "
text025="your_instance_name : rawfifo255x14"
text026="        port map ("
text027="            din => din,"
text028="            wr_en => wr_en,"
text029="            wr_clk => wr_clk,"
text030="            rd_en => rd_en,"
text031="            rd_clk => rd_clk,"
text032="            ainit => ainit,"
text033="            dout => dout,"
text034="            full => full,"
text035="            empty => empty);"
text036=" "
type=template
[COREGEN.VHDL Component Instantiation.spfilter]
text000=" "
text001=" "
text002="-- The following code must appear in the VHDL architecture header:"
text003=" "
text004="component spfilter"
text005="    port ("
text006="    CLK: IN std_logic;"
text007="    RESET: IN std_logic;"
text008="    ND: IN std_logic;"
text009="    RDY: OUT std_logic;"
text010="    RFD: OUT std_logic;"
text011="    DIN: IN std_logic_VECTOR(15 downto 0);"
text012="    DOUT: OUT std_logic_VECTOR(37 downto 0));"
text013="end component;"
text014=""
text015=""
text016=""
text017=" "
text018="-------------------------------------------------------------"
text019=" "
text020="-- The following code must appear in the VHDL architecture body."
text021="-- Substitute your own instance name and net names."
text022=" "
text023="your_instance_name : spfilter"
text024="        port map ("
text025="            CLK => CLK,"
text026="            RESET => RESET,"
text027="            ND => ND,"
text028="            RDY => RDY,"
text029="            RFD => RFD,"
text030="            DIN => DIN,"
text031="            DOUT => DOUT);"
text032=" "
type=template
