-- ==============================================================
-- FILE : HE_SCLK.VHD  -  DO NOT EDIT THIS FILE
-- ==============================================================
--
-- This file is part of the Hardware Interface Layer (H.I.L) of
-- your project when using your HERON-IO4 module.
--
-- This file must NOT be modified by users of the Module.
--
-- ==============================================================
--
--  Module      : HE_SCLK
--  Date        : 04/03/2002
--  Author      : R. Williams - HUNT ENGINEERING
--  Description : ADC Clock
--
-- ==============================================================
--
--  Ver     Modified By      Date      Changes
--  ---     -----------      ----      -------
--  1.0     R. Williams    04-03-02    First Written
--  1.1     R. Williams    08-05-02    Syntax change made to all
--                                     instanciated components,
--                                     (changed '0' to GND)
--                                     for compatibility with
--                                     ModelSim5.5b.
--  2.0     R. Williams    26-11-02    New components added for
--                                     interfacing to all six HERON
--                                     input FIFOs and all six HERON
--                                     output FIFOs at the same time.
--                                     Added component HE_RD_6F in
--                                     place of component HE_RD_1F.
--                                     Added component HE_WR_6F in
--                                     place of component HE_WR_1F.
--  2.1     R. Williams    20-01-03    Changes made to the HSB
--                                     mastering functions, and 
--                                     additional registering added
--                                     to the AE flag to ensure
--                                     correct reading from HEPC8s.
--
-- ==============================================================


library IEEE;
  use IEEE.std_logic_1164.all;

-- synopsys translate_off
library UNISIM;
  use UNISIM.vcomponents.all;
-- synopsys translate_on

entity HE_SCLK is
  generic ( DriveClock : boolean );
  port (
    -- external PADS
    DRDY   : in  std_logic;
    -- module I/Os
    OEN    : out std_logic;
    SCLK   : out std_logic
  );
end HE_SCLK;


architecture RTL of HE_SCLK is

  component BUFG
    port(I : in  std_logic;
         O : out std_logic);
  end component;

  signal OE      : std_logic;

begin

  IntClk : if DriveClock generate
    OE <= '0';
  end generate;

  ExtClk : if (NOT DriveClock) generate
    OE <= '1';
  end generate;

  OEN <= OE;
  
  iSCLK : BUFG port map (I=>DRDY, O=>SCLK); 

end RTL;

