-- ==============================================================
-- FILE : HE_RWCLK.VHD  -  DO NOT EDIT THIS FILE
-- ==============================================================
--
-- This file is part of the Hardware Interface Layer (H.I.L) of
-- your project when using your HERON-IO4 module.
--
-- This file must NOT be modified by users of the Module.
--
-- ==============================================================
--
--  Module      : HE_RWCLK
--  Date        : 04/03/2002
--  Author      : R. Williams - HUNT ENGINEERING
--  Description : FIFO Clock, same for the IN and OUT FIFOs
--
-- ==============================================================
--
--  Notes :
--  -1-  when FIFO read/write clock frequency > 60 MHz,
--       HFreq must be set to TRUE.
--  -2-  Using CLKDLL primitives (inspite of DCM for Virtex2)
--       for source code compatibilty with Spartan2.
--
-- ==============================================================
--
--  Ver     Modified By      Date      Changes
--  ---     -----------      ----      -------
--  1.0     R. Williams    04-03-02    First Written
--  1.1     R. Williams    08-05-02    Syntax change made to all
--                                     instanciated components,
--                                     (changed '0' to GND)
--                                     for compatibility with
--                                     ModelSim5.5b.
--  2.0     R. Williams    26-11-02    New components added for
--                                     interfacing to all six HERON
--                                     input FIFOs and all six HERON
--                                     output FIFOs at the same time.
--                                     Added component HE_RD_6F in
--                                     place of component HE_RD_1F.
--                                     Added component HE_WR_6F in
--                                     place of component HE_WR_1F.
--  2.1     R. Williams    20-01-03    Changes made to the HSB
--                                     mastering functions, and 
--                                     additional registering added
--                                     to the AE flag to ensure
--                                     correct reading from HEPC8s.
--
-- ==============================================================


library IEEE;
  use IEEE.std_logic_1164.all;

-- synopsys translate_off
library UNISIM;
  use UNISIM.vcomponents.all;
-- synopsys translate_on

entity HE_RWCLK is
  generic ( HFreq : boolean := FALSE );
  port (
    -- External PADS
    DCLK : in  std_logic;
    FCLK : out std_logic;
    -- Module I/Os
    RST  : in  std_logic;
    CLK  : in  std_logic;
    GCLK : out std_logic
  );
end HE_RWCLK;


architecture RTL of HE_RWCLK is

  component CLKDLL
    port (CLKIN   : in  std_logic;
          CLKFB   : in  std_logic;
          RST     : in  std_logic;
          CLK0    : out std_logic;
          CLK90   : out std_logic;
          CLK180  : out std_logic;
          CLK270  : out std_logic;
          CLK2X   : out std_logic;
          CLKDV   : out std_logic;
          LOCKED  : out std_logic);
  end component;

  component CLKDLLHF
    port (CLKIN  : in  std_logic;
          CLKFB  : in  std_logic;
          RST    : in  std_logic;
          CLK0   : out std_logic;
          CLK180 : out std_logic;
          CLKDV  : out std_logic;
          LOCKED : out std_logic);
  end component;

  component BUFG
    port(I : in  std_logic;
         O : out std_logic);
  end component;

  component FDP
    port(
      Q   : out std_logic;
      D   : in  std_logic;
      C   : in  std_logic;
      PRE : in  std_logic);
  end component;

  signal GND     : std_logic;
  signal R1      : std_logic;
  signal R2      : std_logic;
  signal RST_DLL : std_logic;
  signal CLKIN   : std_logic;
  signal CLK0    : std_logic;
  signal GCLK0   : std_logic;

begin

  GND <= '0';

  FCLK <= CLK;    -- OBUF_F_24 (instanciation in the top level)

  CLKIN <= DCLK;  -- IBUFG (instanciation in the top level)

  gHFclk : if HFreq generate
    process(CLK)
    begin
      if rising_edge(CLK) then
        RST_DLL <= R2 AND (NOT R1);
      end if;
    end process;

    iFDP0: FDP
      port map ( Q    => R1,
                 D    => RST,
                 C    => CLK,
                 PRE  => GND );

    iFDP1: FDP
      port map ( Q    => R2,
                 D    => R1,
                 C    => CLK,
                 PRE  => GND );

    iDLL : CLKDLLHF
      port map ( CLKIN => CLKIN,
                 CLKFB => GCLK0,
                 RST   => RST_DLL,
                 CLK0  => CLK0 );
  end generate;

  gLFclk : if (NOT HFreq) generate
    iDLL : CLKDLL
      port map ( CLKIN => CLKIN,
                 CLKFB => GCLK0,
                 RST   => GND,
                 CLK0  => CLK0 );
  end generate;

  bGCK : BUFG port map (I=>CLK0, O=>GCLK0);
  GCLK <= GCLK0;

end RTL;

